-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cart
(
    users smallint NOT NULL,
    videogames smallint NOT NULL,
    quantity numeric(4, 2),
    CONSTRAINT cart_pkey PRIMARY KEY (users, videogames)
);

CREATE TABLE IF NOT EXISTS public.order_videogames
(
    orders integer NOT NULL,
    videogame integer NOT NULL,
    price numeric(3, 2),
    quantity numeric(4, 2),
    CONSTRAINT order_videogames_pkey PRIMARY KEY (orders, videogame)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
    users smallint NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default",
    password character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.videogames
(
    id integer NOT NULL DEFAULT nextval('videogames_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default",
    price numeric(3, 2),
    CONSTRAINT videogames_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT cart_users_fkey FOREIGN KEY (users)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT cart_videogames_fkey FOREIGN KEY (videogames)
    REFERENCES public.videogames (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_videogames
    ADD CONSTRAINT order_videogames_orders_fkey FOREIGN KEY (orders)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_videogames
    ADD CONSTRAINT order_videogames_videogame_fkey FOREIGN KEY (videogame)
    REFERENCES public.videogames (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_users_fkey FOREIGN KEY (users)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;